
#ifndef TUNE_H
#define TUNE_H

#ifndef M_PI
#define M_PI 3.14159265358979323846
#endif

const double M_2PI = 2 * M_PI;
const double M_PI2 = 0.5 * M_PI;
const double RAD   = 180. / M_PI;

#ifndef M_SQRT2
#define M_SQRT2 1.41421356237309504880
#endif

//#define VECTOR3D_H_IN_FILESTL_CPP

#define VECTOR2D_H_IN_RAND_CPP
#define VECTOR3D_H_IN_RAND_CPP
//#define VECTOR3F_H_IN_RAND_CPP
#define VECTOR4D_H_IN_RAND_CPP

#endif
